language: node_js
node_js:
  - "6"
  - "7"
  - "8"

os:
  - linux
  - osx

script:
  - npm test
  - npm run lint

# Maybe have a loot at https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
#jobs:
#  include:
#    - stage: docs
#      node_js: "6"
#      script: npm run docs
#      deploy:
#        provider: pages
#        skip_cleanup: true
#        github_token: ${GH_TOKEN}
#        on:
#          branch: master
