language: node_js
node_js:
  - "6"
  - "7"
  - "8"
script:
  - npm test
  - npm run lint

jobs:
  include:
    - stage: npm release
      node_js: "7"
      script: npm run docs && git add docs
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: ${GH_TOKEN}
        on:
          branch: master
