language: node_js
node_js:
  - "6"
  - "7"
  - "8"
script:
  - npm test
  - npm run lint
  - npm run docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  on:
    branch: master
